### ISSUE TITLE
Unable to run in Forge

### ISSUE THREAD

**Issue by jdnjk** [andrei1058/BedWars1058#1013]
**Describe the bug**
[20:35:48 INFO]: [BedWars1058] Enabling BedWars1058 v23.12.2
[20:35:48 ERROR]: Error occurred while enabling BedWars1058 v23.12.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.andrei1058.bedwars.API.setRestoreAdapter(API.java:347) ~[?:?]
        at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:222) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:471) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:397) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:478) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:368) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:220) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:828) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.configuration.MainConfig.getInt(String)" because "com.andrei1058.bedwars.BedWars.config" is null
        at com.andrei1058.bedwars.arena.Arena.<clinit>(Arena.java:112) ~[?:?]
        ... 13 more
[20:35:48 INFO]: [BedWars1058] Disabling BedWars1058 v23.12.2
[20:35:48 ERROR]: Error occurred while disabling BedWars1058 v23.12.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.andrei1058.bedwars.arena.Arena
        at com.andrei1058.bedwars.BedWars.onDisable(BedWars.java:593) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:500) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:471) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:397) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:478) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:368) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:220) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:828) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
        at com.andrei1058.bedwars.arena.Arena.<clinit>(Arena.java:112) ~[?:?]
        at com.andrei1058.bedwars.API.setRestoreAdapter(API.java:347) ~[?:?]
        at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:222) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge-1.18.2-40.2.17-universal.jar%2367!/:?]
        ... 9 more

**System (please complete the following information):**
 - OS: Debian Linux
 - Server software Mohist
 - Server Version 1.18.2
 - Plugin Version 23.12.2

**Comment by WitheredWinter** [comment]
BedWars1058 doesn't intend to support Forge servers
![image](https://github.com/andrei1058/BedWars1058/assets/123742753/597c107b-86d2-4f50-bcc8-060cf3636bc9)
What can I say. Man!
