### ISSUE TITLE
TNT source

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/BedWars1058#1040]
**Describe the bug**

Setting tnt source via nms throws error in 1.21

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software 
 - Server Version 
 - Plugin Version 
 24.8

**Additional context**

```
[18:35:44] [Server thread/WARN]: java.lang.IllegalAccessException: Can not set static final net.minecraft.network.syncher.DataWatcherObject field net.minecraft.world.entity.item.EntityTNTPrimed.d to net.minecraft.server.level.EntityPlayer
[18:35:44] [Server thread/WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwFinalFieldIllegalAccessException(FieldAccessorImpl.java:137)
[18:35:44] [Server thread/WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwFinalFieldIllegalAccessException(FieldAccessorImpl.java:141)
[18:35:44] [Server thread/WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:103)
[18:35:44] [Server thread/WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:836)
[18:35:44] [Server thread/WARN]:        at com.andrei1058.bedwars.support.version.v1_21_R1.v1_21_R1.setSource(v1_21_R1.java:65)
[18:35:44] [Server thread/WARN]:        at com.andrei1058.bedwars.listeners.BreakPlace.onBlockPlace(BreakPlace.java:174)
[18:35:44] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:35:44] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:35:44] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:35:44] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:35:44] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601)
[18:35:44] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588)
[18:35:44] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:452)
[18:35:44] [Server thread/WARN]:        at net.minecraft.world.item.ItemStack.a(ItemStack.java:483)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:565)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1585)
[18:35:44] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:44)
[18:35:44] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:11)
[18:35:44] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[18:35:44] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162)
[18:35:44] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203)
[18:35:44] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242)
[18:35:44] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078)
[18:35:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[18:35:44] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by andrei1058** [comment]
https://github.com/andrei1058/BedWars1058/issues/1031

**Comment by andrei1058** [comment]
![Image](https://github.com/user-attachments/assets/9ad4f33e-c653-4ce7-8b95-463ce12f31d5)

source fixed. but the plugin does not give a reward to the one who placed the tnt it seems
