### ISSUE TITLE
Error after respawn

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/BedWars1058#1041]
**Describe the bug**

**To Reproduce**

void kill, respawn, console error

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software 
 - Server Version 
 - Plugin Version 
 v24.8

**Additional context**

```
[18:41:36] [Server thread/WARN]: [BedWars1058] Task #1531 for BedWars1058 v24.8-SNAPSHOT generated an exception
java.lang.RuntimeException: Something went wrong... please report this to BedWars1058 by andrei1058
        at com.andrei1058.bedwars.support.version.v1_21_R1.v1_21_R1.getPlayerSpawnAction(v1_21_R1.java:223) ~[?:?]
        at com.andrei1058.bedwars.support.version.v1_21_R1.v1_21_R1.getAddPlayer(v1_21_R1.java:74) ~[?:?]
        at dev.andrei1058.mc.bedwars.AbstractVerImplCmn1.sendPlayerSpawnPackets(AbstractVerImplCmn1.java:541) ~[?:?]
        at com.andrei1058.bedwars.arena.team.BedWarsTeam.lambda$respawnMember$4(BedWarsTeam.java:428) ~[?:?]
        at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1425) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]

```

**Comment by andrei1058** [comment]
https://github.com/andrei1058/BedWars1058/issues/1031
