### ISSUE TITLE
Error in console Cannot invoke "java.util.List.contains(Object)" because "this.players" is null

### ISSUE THREAD

**Issue by krystian987** [andrei1058/BedWars1058#1051]
[18:23:22] [Server thread/WARN]: [BedWars1058] Task #679186 for BedWars1058 v24.9 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "this.players" is null
	at com.andrei1058.bedwars.arena.Arena.isPlayer(Arena.java:1576) ~[?:?]
	at com.andrei1058.bedwars.arena.Arena.lambda$addPlayer$4(Arena.java:575) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:840) [?:?]

**Describe the bug**
The error occurs randomly, I don't know what it depends on

**System:**
 - OS: Linux
 - Server software: Paper
 - Server Version: 1.12.2
 - Plugin Version: 24.9

**Comment by andrei1058** [comment]
plugin list?
