### ISSUE TITLE
Scoreboard Error Issue 

### ISSUE THREAD

**Issue by NovaPixell** [andrei1058/BedWars1058#199]
**Describe the bug**
With a large amount of players I have encountered this problem on the console.
With the following error in console.
Unfortunately, graphically I don't know what the player was viewing
(I haven't any plugins that modify/access to scoreboard)

**To Reproduce**
1. Finish/Quit a BedWars game.

**Error**
```
[16:01:45] [Server thread/INFO]: USER[/xxxx:xxxx] logged in with entity id 504950 at ([lobby]-3.583838774084099, 99.5, 10.790361294051321)
[16:01:45] [Craft Scheduler Thread - 1655/WARN]: Exception in thread "Craft Scheduler Thread - 1655" 
[16:01:45] [Craft Scheduler Thread - 1655/WARN]: org.apache.commons.lang.UnhandledException: Plugin BedWars1058 v21.11.2 generated an exception while executing task 33
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1474)
	at com.andrei1058.bedwars.sidebar.SidebarTitleRefresh.run(SidebarTitleRefresh.java:26)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

**System (please complete the following information):**
 - OS: Linux
 - Server software Spigot
 - Server Version 1.8.8
 - Plugin Version 21.11.2

**Comment by PikaMug** [comment]
From what I can tell, this is because the iterator of this HashMap
https://github.com/andrei1058/BedWars1058/blob/3f210ef5a761b06b82609f3562c4e1d9c77895ed/bedwars-plugin/src/main/java/com/andrei1058/bedwars/sidebar/BedWarsScoreboard.java#L51
is not meant to be used by multiple threads. The easiest solution would be to make this a ConcurrentHashMap instead, but a lockable syncronizedMap or Hashtable should also be considered.

**Comment by andrei1058** [comment]
> From what I can tell, this is because the iterator of this HashMap
> 
> https://github.com/andrei1058/BedWars1058/blob/3f210ef5a761b06b82609f3562c4e1d9c77895ed/bedwars-plugin/src/main/java/com/andrei1058/bedwars/sidebar/BedWarsScoreboard.java#L51
> 
> 
> is not meant to be used by multiple threads. The easiest solution would be to make this a ConcurrentHashMap instead, but a lockable syncronizedMap or Hashtable should also be considered.

It does work with multiple threads. They're all supposed to be **sync**.

@NovaPixell I need your plugin list, especially bw addons.

**Comment by NovaPixell** [comment]
> > From what I can tell, this is because the iterator of this HashMap
> > https://github.com/andrei1058/BedWars1058/blob/3f210ef5a761b06b82609f3562c4e1d9c77895ed/bedwars-plugin/src/main/java/com/andrei1058/bedwars/sidebar/BedWarsScoreboard.java#L51
> > 
> > is not meant to be used by multiple threads. The easiest solution would be to make this a ConcurrentHashMap instead, but a lockable syncronizedMap or Hashtable should also be considered.
> 
> It does work with multiple threads. They're all supposed to be **sync**.
> 
> @NovaPixell I need your plugin list, especially bw addons.

![Cattura](https://user-images.githubusercontent.com/55632135/147384399-02259549-f3ab-437d-875b-ba0ce5901316.PNG)
Here!

**Comment by PikaMug** [comment]
> It does work with multiple threads. They're all supposed to be **sync**.

The entries might be sync, but I don't see where you've explicitly synchronized the HashMap itself. Since not, its iterator shouldn't be used by multiple threads while the collection is being modified. It may work most of the time, but when too many requests (read: players) are present, this happens.

Yes, it _could_ be one of those BedWars modules or another plugin contributing to the exception, but isn't the solution the same? Especially if you intend on keeping getScoreboards() and remove() publicly accessible?

**Comment by tomkeuper** [comment]
Closed due to scoreboard overhaul. Any new issues with the latest version should be reported in a new issue
