### ISSUE TITLE
Not compatible with 1.17

### ISSUE THREAD

**Issue by PikaMug** [andrei1058/BedWars1058#205]
**Describe the bug**
Upon joining the server, the following error is repeated:
```
[03:58:35] [Server thread/WARN]: [BedWars1058] Task #19 for BedWars1058 v${gitVer}21.12 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer net.minecraft.server.network.PlayerConnection.getPlayer()'
	at com.andrei1058.bedwars.libs.sidebar.Sidebar_v1_17_R1$ScoreLine.setContent(Sidebar_v1_17_R1.java:514) ~[bedwars-plugin-21.12.jar:?]
	at com.andrei1058.bedwars.libs.sidebar.Sidebar_v1_17_R1.refreshPlaceholders(Sidebar_v1_17_R1.java:142) ~[bedwars-plugin-21.12.jar:?]
	at com.andrei1058.bedwars.sidebar.SidebarPlaceholderRefresh.run(SidebarPlaceholderRefresh.java:27) ~[bedwars-plugin-21.12.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-401]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-401]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-401]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-401]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-401]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-401]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-401]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**To Reproduce**
1. Compile and run 21.12 on MC 1.17 server.
2. Join server.
3. Scoreboard appears, but console is spammed.

**Expected behavior**
No error.

**System (please complete the following information):**
 - OS: Win10
 - Server software - Paper
 - Server Version - git-Paper-401 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5bd2611 on ver/1.17.1)
 - Plugin Version - 21.12

**Additional context**
I think the only method might be .d() in this version?

**Comment by PikaMug** [comment]
Side note: This does not occur on 1.18 under the same conditions.

**Comment by andrei1058** [comment]
fixed (update snapshot versions)
