### ISSUE TITLE
Items being dropped when they shouldn't be

### ISSUE THREAD

**Issue by nicegamer7** [andrei1058/BedWars1058#274]
**Describe the bug**
Items are dropped when they aren't supposed to be. For example, when killing a player, they drop their all their items. Another example is when you break a team's bed, you're able to pick it up. Additionally, I find this error in the console several times:
```
[06:26:30 ERROR]: Could not pass event PlayerDeathEvent to BedWars1058 v${gitVer}21.12.1
java.lang.IllegalStateException: Registering datawatcher object after entity initialization
	at net.minecraft.network.syncher.SynchedEntityData.define(SynchedEntityData.java:84) ~[?:?]
	at com.andrei1058.bedwars.support.version.v1_18_R1.v1_18_R1.clearArrowsFromPlayerBody(v1_18_R1.java:698) ~[bedwars-plugin-21.12.1.jar:?]
	at com.andrei1058.bedwars.listeners.DamageDeathMove.onDeath(DamageDeathMove.java:349) ~[bedwars-plugin-21.12.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor51.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-140]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:896) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:862) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1451) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:923) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1027) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1263) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2035) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2519) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2446) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-140]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-140]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**
1. Set up an arena on a 1.18.1 server.
2. Play as normal.
3. Observe behavior described above.

**Expected behavior**
I'm pretty sure you shouldn't be able to pick up a player's items when they die. And I'm near certain you shouldn't be able to pick up a team bed when it's broken.

**System**
 - OS: Linux
 - Server Software: git-Paper-140
 - Server Version: 1.18.1
 - Plugin Version: v21.12.1

**Additional context**
- BedWars1058 is in SHARED mode, and the game was joined using a sign.
- Multiverse is installed, but the game world is not being managed by Multiverse.
- Plugins: BedWars1058, CoreProtect, DynamicIcon, Essentials, EssentialsSpawn, Harbor, LuckPerms, LWC, LWCTrust, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, ProtocolLib, Vault.

**Comment by ghost** [comment]
https://github.com/andrei1058/BedWars1058/issues/236
I already reported it

**Comment by nicegamer7** [comment]
Ah right. I tried to search for the event in the error, bit since you used a paste service it didn't show up. No worries, thanks for pointing it out!
