### ISSUE TITLE
sql bug

### ISSUE THREAD

**Issue by xcoolerboy** [andrei1058/BedWars1058#28]
[14:35:06 WARN]: java.sql.SQLTransientConnectionException: BedWars1058MySQLPool
- Connection is not available, request timed out after 30001ms.
[14:35:06 WARN]:        at com.andrei1058.bedwars.libs.hikari.pool.HikariPool.cr
eateTimeoutException(HikariPool.java:695)
[14:35:06 WARN]:        at com.andrei1058.bedwars.libs.hikari.pool.HikariPool.ge
tConnection(HikariPool.java:197)
[14:35:06 WARN]:        at com.andrei1058.bedwars.libs.hikari.pool.HikariPool.ge
tConnection(HikariPool.java:162)
[14:35:06 WARN]:        at com.andrei1058.bedwars.libs.hikari.HikariDataSource.g
etConnection(HikariDataSource.java:100)
[14:35:06 WARN]:        at com.andrei1058.bedwars.database.MySQL.getLanguage(MyS
QL.java:457)
[14:35:06 WARN]:        at com.andrei1058.bedwars.listeners.joinhandler.JoinHand
lerCommon.requestLanguage(JoinHandlerCommon.java:60)
[14:35:06 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[14:35:06 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[14:35:06 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[14:35:06 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:35:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(Jav
aPluginLoader.java:300)
[14:35:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEven
tExecutor.java:74)
[14:35:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(Regist
eredListener.java:62)
[14:35:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(Simpl
ePluginManager.java:517)
[14:35:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(Simpl
ePluginManager.java:499)
[14:35:06 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener$LoginHandl
er.fireEvents(LoginListener.java:248)
[14:35:06 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener$2.run(Logi
nListener.java:172)
[14:35:06 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:35:06 INFO]: com.mojang.authlib.GameProfile@a92f28d[id=efe05f42-1fe7-3e51-b1
93-7051d570da5a,name=danieladz,properties={textures=[com.mojang.authlib.properti
es.Property@7ef67a6a], bungeeguard-token=[com.mojang.authlib.properties.Property
@10631a2]},legacy=false] (/80.200.50.45:57687) lost connection: Timed out

**Comment by andrei1058** [comment]
It was fixed today. We will release the new update soon. Next time you report an issue please fill in the bug template! Thank you
