### ISSUE TITLE
Chat Disable In Client Option!

### ISSUE THREAD

**Issue by UntowardAbdullah** [andrei1058/BedWars1058#301]
After setting up the Lobby, after joining game, when I'm trying to send a message, it says "Chat disabled in Client options"
and gives the following error In server Console:

[BedWars1058] Plugin BedWars1058 v${gitVer}21.12.1 generated an exception while executing task 6555
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:397) ~[app:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:662) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:653) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.network.protocol.game.ClientboundContainerSetSlotPacket.<init>(ClientboundContainerSetSlotPacket.java:21) ~[app:?]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113) ~[patched_1.17.1.jar:git-Paper-408]
	at com.andrei1058.bedwars.arena.Arena.lambda$sendLobbyCommandItems$14(Arena.java:1665) ~[bedwars-plugin-21.12.1.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-408]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-408]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:06:41 ERROR]: Entity threw exception at Bedwars2:0.5615897787811736,60.0,0.6639610105626109
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:397) ~[app:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:662) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:653) ~[patched_1.17.1.jar:git-Paper-408]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:166) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:289) ~[app:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:234) ~[app:?]
	at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:637) ~[app:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1120) ~[app:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:977) ~[app:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]	
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
![error](https://user-images.githubusercontent.com/97896251/149786759-71e8e01e-f9bf-4fa1-a391-ce7f3794cce4.png)

**Comment by ajgeiss0702** [comment]
Please check for already existing issues before creating a new one

**Comment by UntowardAbdullah** [comment]
> Please check for already existing issues before creating a new one

Sorry But I Can't See This Issue Solution!!

**Comment by ajgeiss0702** [comment]
The solution is to wait for bedwars to fully support 1.17/1.18

**Comment by UntowardAbdullah** [comment]
> The solution is to wait for bedwars to fully support 1.17/1.18

When This Plugin Support 1.18 Fully?
