### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by xcoolerboy** [andrei1058/BedWars1058#33]
[Craft Scheduler Thread - 1/WARN]: java.sql.SQLException: [SQLITE_MISUSE]  Library used incorrectly (out of memory)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:404)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:399)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:383)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at com.andrei1058.bedwars.database.SQLite.setLevelData(SQLite.java:318)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at com.andrei1058.bedwars.levels.internal.PlayerLevel.lambda$updateDatabase$0(PlayerLevel.java:247)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 28/WARN]: Exception in thread "Craft Scheduler Thread - 28" 
[02:16:07] [Craft Scheduler Thread - 28/WARN]: org.apache.commons.lang.UnhandledException: Plugin BedWars1058 v${gitVer}21.10.1-SNAPSHOT generated an exception while executing task 13150
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
	at org.sqlite.Conn.prepareStatement(Conn.java:404)
	at org.sqlite.Conn.prepareStatement(Conn.java:399)
	at org.sqlite.Conn.prepareStatement(Conn.java:383)
	at com.andrei1058.bedwars.database.SQLite.pushQuickBuyChanges(SQLite.java:422)
	at com.andrei1058.bedwars.shop.quickbuy.PlayerQuickBuyCache.lambda$pushChangesToDB$1(PlayerQuickBuyCache.java:162)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[02:16:07] [Craft Scheduler Thread - 3/WARN]: java.sql.SQLException: [SQLITE_MISUSE]  Library used incorrectly (out of memory)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:404)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:399)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:383)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at com.andrei1058.bedwars.database.SQLite.hasStats(SQLite.java:126)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at com.andrei1058.bedwars.database.SQLite.saveStats(SQLite.java:142)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at com.andrei1058.bedwars.stats.StatsListener.lambda$onArenaLeave$0(StatsListener.java:188)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: java.sql.SQLException: [SQLITE_MISUSE]  Library used incorrectly (out of memory)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.sqlite.Stmt.executeQuery(Stmt.java:121)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at com.andrei1058.bedwars.database.SQLite.hasQuickBuy(SQLite.java:265)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at com.andrei1058.bedwars.database.SQLite.pushQuickBuyChanges(SQLite.java:391)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at com.andrei1058.bedwars.shop.quickbuy.PlayerQuickBuyCache.lambda$pushChangesToDB$1(PlayerQuickBuyCache.java:162)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 77/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:16:07] [Craft Scheduler Thread - 3/WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[02:16:07] [Craft Scheduler Thread - 3/WARN]: org.apache.commons.lang.UnhandledException: Plugin BedWars1058 v${gitVer}21.10.1-SNAPSHOT generated an exception while executing task 13203
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
	at org.sqlite.Conn.prepareStatement(Conn.java:404)
	at org.sqlite.Conn.prepareStatement(Conn.java:399)
	at org.sqlite.Conn.prepareStatement(Conn.java:383)
	at com.andrei1058.bedwars.database.SQLite.saveStats(SQLite.java:162)
	at com.andrei1058.bedwars.stats.StatsListener.lambda$onArenaLeave$0(StatsListener.java:188)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[02:16:07] [Craft Scheduler Thread - 77/WARN]: Exception in thread "Craft Scheduler Thread - 77" 
[02:16:07] [Craft Scheduler Thread - 77/WARN]: org.apache.commons.lang.UnhandledException: Plugin BedWars1058 v${gitVer}21.10.1-SNAPSHOT generated an exception while executing task 13201
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
	at org.sqlite.Conn.prepareStatement(Conn.java:404)
	at org.sqlite.Conn.prepareStatement(Conn.java:399)
	at org.sqlite.Conn.prepareStatement(Conn.java:383)
	at com.andrei1058.bedwars.database.SQLite.pushQuickBuyChanges(SQLite.java:422)
	at com.andrei1058.bedwars.shop.quickbuy.PlayerQuickBuyCache.lambda$pushChangesToDB$1(PlayerQuickBuyCache.java:162)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[02:16:07] [Server thread/WARN]: handleDisconnection() called twice
[02:16:07] [Server thread/WARN]: handleDisconnection() called twice
[02:16:07] [Server thread/WARN]: handleDisconnection() called twice
[02:16:07] [Server thread/WARN]: handleDisconnection() called twice
[02:16:07] [Server thread/WARN]: handleDisconnection() called twice

**Comment by minhh2792** [comment]
out of memory ?

**Comment by DieselJS** [comment]
Can you provide more information on the server container (the RAM usage, how much is allocated, etc.) SQLite states an out of memory in the log, so it could be that. Maybe try adding more RAM/storage even?
