### ISSUE TITLE
Missing level tag

### ISSUE THREAD

**Issue by Ralphaf** [andrei1058/BedWars1058#368]
[18:09:20 ERROR]: Error occurred while enabling BedWars1058 v${gitVer}21.12.1 (Is it up to date?)
java.lang.RuntimeException: Missing Level tag?
        at com.grinderwolf.swm.plugin.world.importer.WorldImporter.lambda$loadChunks$7(WorldImporter.java:177) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.grinderwolf.swm.plugin.world.importer.WorldImporter.loadChunks(WorldImporter.java:187) ~[?:?]
        at com.grinderwolf.swm.plugin.world.importer.WorldImporter.readFromDirectory(WorldImporter.java:64) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.importWorld(SWMPlugin.java:395) ~[?:?]
        at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.convertWorld(SlimeAdapter.java:365) ~[?:?]
        at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.convertWorlds(SlimeAdapter.java:333) ~[?:?]
        at com.andrei1058.bedwars.BedWars.loadArenasAndSigns(BedWars.java:590) ~[?:?]
        at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:336) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[18:09:20 INFO]: [BedWars1058] Disabling BedWars1058 v${gitVer}21.12.1

**Comment by ajgeiss0702** [comment]
1. You didn’t use the issue format
2. This is an error from swm, not bedwars
