### ISSUE TITLE
invalid error and server freeze

### ISSUE THREAD

**Issue by TheWylot** [andrei1058/BedWars1058#379]
**Describe the bug**
bedwars1058 execute an error about maincommand and all of the cmds like join disabled and freeze

**To Reproduce**
1. my memory is full at all

**Expected behavior**

**System (please complete the following information):**
 - OS: [Windows Server 2019]
 - Server software [Paper]
 - Server Version [1.8.8]
 - Plugin Version [21.12.1]

**Additional context**
org.bukkit.command.CommandException: Unhandled exception executing 'bw join Doubles' in com.andrei1058.bedwars.commands.bedwars.MainCommand(bw)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1105) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:334) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.citizensnpcs.trait.CommandTrait$NPCCommand.run(CommandTrait.java:475) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.trait.CommandTrait$1$3.run(CommandTrait.java:259) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.trait.CommandTrait$1.runCommand(CommandTrait.java:264) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.trait.CommandTrait$1.run(CommandTrait.java:230) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.trait.CommandTrait.dispatch(CommandTrait.java:271) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:498) [Citizens-2.0.29-b2433.jar:?]
	at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [patched_1.8.8.jar:git-PaperSpigot-445]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1342) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(Unknown Source) ~[?:1.8.0_301]
	at java.util.TimSort.mergeAt(Unknown Source) ~[?:1.8.0_301]
	at java.util.TimSort.mergeCollapse(Unknown Source) ~[?:1.8.0_301]
	at java.util.TimSort.sort(Unknown Source) ~[?:1.8.0_301]
	at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_301]
	at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_301]
	at com.andrei1058.bedwars.arena.Arena.getSorted(Arena.java:2215) ~[?:?]
	at com.andrei1058.bedwars.arena.Arena.joinRandomFromGroup(Arena.java:2250) ~[?:?]
	at com.andrei1058.bedwars.commands.bedwars.subcmds.regular.CmdJoin.execute(CmdJoin.java:69) ~[?:?]
	at com.andrei1058.bedwars.commands.bedwars.MainCommand.execute(MainCommand.java:149) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	... 30 more
Collapse
message.txt
5 KB
i'm getting this error, server freeze and players will disconnect
﻿
org.bukkit.command.CommandException: Unhandled exception executing 'bw join Doubles' in com.andrei1058.bedwars.commands.bedwars.MainCommand(bw)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1105) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:334) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.citizensnpcs.trait.CommandTrait$NPCCommand.run(CommandTrait.java:475) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.trait.CommandTrait$1$3.run(CommandTrait.java:259) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.trait.CommandTrait$1.runCommand(CommandTrait.java:264) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.trait.CommandTrait$1.run(CommandTrait.java:230) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.trait.CommandTrait.dispatch(CommandTrait.java:271) [Citizens-2.0.29-b2433.jar:?]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:498) [Citizens-2.0.29-b2433.jar:?]
	at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [patched_1.8.8.jar:git-PaperSpigot-445]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1342) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(Unknown Source) ~[?:1.8.0_301]
	at java.util.TimSort.mergeAt(Unknown Source) ~[?:1.8.0_301]
	at java.util.TimSort.mergeCollapse(Unknown Source) ~[?:1.8.0_301]
	at java.util.TimSort.sort(Unknown Source) ~[?:1.8.0_301]
	at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_301]
	at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_301]
	at com.andrei1058.bedwars.arena.Arena.getSorted(Arena.java:2215) ~[?:?]
	at com.andrei1058.bedwars.arena.Arena.joinRandomFromGroup(Arena.java:2250) ~[?:?]
	at com.andrei1058.bedwars.commands.bedwars.subcmds.regular.CmdJoin.execute(CmdJoin.java:69) ~[?:?]
	at com.andrei1058.bedwars.commands.bedwars.MainCommand.execute(MainCommand.java:149) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	... 30 more

**Comment by Xxyuri2005xX** [comment]
Please complete the template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. MacOS, Windows Server, Linux]
 - Server software [e.g. spigot, paper]
 - Server Version [e.g. 1.8.8]
 - Plugin Version [e.g. 21.11.2]

**Additional context**
Add any other context about the problem here.

And give console error in a Paste link if possible, thanks

**Comment by TheWylot** [comment]
@Xxyuri2005xX updated report bug template.

**Comment by ghost** [comment]
I have server freezing problem too

**Comment by tomkeuper** [comment]
Is this still accurate with the latest version?
