### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by PersianDevs** [andrei1058/BedWars1058#387]
[BedWars1058] Task #820 for BedWars1058 v${gitVer}21.12.1 generated an exception
java.lang.IllegalArgumentException: World crogorm-doubles already exists! Maybe it's an outdated SlimeWorld object?
        at com.grinderwolf.swm.nms.v1_8_R3.v1_8_R3SlimeNMS.addWorldToServerList(v1_8_R3SlimeNMS.java:102) ~[?:?]
        at com.grinderwolf.swm.nms.v1_8_R3.v1_8_R3SlimeNMS.generateWorld(v1_8_R3SlimeNMS.java:89) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.generateWorld(SWMPlugin.java:324) ~[?:?]
        at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.lambda$onEnable$1(SlimeAdapter.java:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[FeatherMC.jar:1.8.8]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [FeatherMC.jar:1.8.8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:794) [FeatherMC.jar:1.8.8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) [FeatherMC.jar:1.8.8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [FeatherMC.jar:1.8.8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617) [FeatherMC.jar:1.8.8]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**System (please complete the following information):**
 - Windows
 - PaperSpigot
 - 1.8.8
 - Plugin Version: 21.12.1

**Comment by tomkeuper** [comment]
SWM error. Probably caused by a crash.
