### ISSUE TITLE
Paper 1.17 | Version support error?

### ISSUE THREAD

**Issue by BaterWucket** [andrei1058/BedWars1058#397]
Running Paper 1.17
After starting server got this error: 

```
[20:16:11] [Server thread/INFO]: [BedWars1058] Enabling BedWars1058 v22.2
[20:16:11] [Server thread/ERROR]: Error occurred while enabling BedWars1058 v22.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.api.server.VersionSupport.registerVersionListeners()" because "com.andrei1058.bedwars.BedWars.nms" is null
    at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:201) ~[bedwars-plugin-22.2.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-349]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-349]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
    at java.lang.Thread.run(Thread.java:831) ~[?:?]
[20:16:11] [Server thread/INFO]: [BedWars1058] Disabling BedWars1058 v22.2
[20:16:11] [Server thread/ERROR]: Error occurred while disabling BedWars1058 v22.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
    at com.andrei1058.bedwars.BedWars.onDisable(BedWars.java:585) ~[bedwars-plugin-22.2.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-349]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-349]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-349]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
    at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.configuration.MainConfig.getInt(String)" because "com.andrei1058.bedwars.BedWars.config" is null
    at com.andrei1058.bedwars.arena.Arena.<clinit>(Arena.java:105) ~[bedwars-plugin-22.2.jar:?]
    ... 12 more
    
```

**Comment by ghost** [comment]
better use bedwars1058 with versions under 1.13

**Comment by minhh2792** [comment]
> better us bedwars1058 with versions under 1.13

This plugin support from 1.8 - 1.18, it is better for you to shut up for a while. Stop spreading false information

**Comment by ghost** [comment]
> > better us bedwars1058 with versions under 1.13
> 
> This plugin support from 1.8 - 1.18, it is better for you to shut up for a while. Stop spreading false information

None of you business dumpoooooooo.
I just recommented not forced.
also i didnt told it doesnt support.
it supports but have too much bugs on higher versions.
So stop the f up you dumpoo.
and never judge me.

**Comment by ajgeiss0702** [comment]
> > > better us bedwars1058 with versions under 1.13
> > 
> > 
> > This plugin support from 1.8 - 1.18, it is better for you to shut up for a while. Stop spreading false information
> 
> None of you business dumpoooooooo. I just recommented not forced. also i didnt told it doesnt support. it supports but have too much bugs on higher versions. So stop the f up you dumpoo. and never judge me.

The plugin supports higher versions. They have bugs, yes. This is the place to report bugs so of course you’re going to see bugs here. Harassing people for using a newer version is not helping anyone

**Comment by TipizYT** [comment]
> Running Paper 1.17 After starting server got this error:
> 
> ```
> [20:16:11] [Server thread/INFO]: [BedWars1058] Enabling BedWars1058 v22.2
> [20:16:11] [Server thread/ERROR]: Error occurred while enabling BedWars1058 v22.2 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.api.server.VersionSupport.registerVersionListeners()" because "com.andrei1058.bedwars.BedWars.nms" is null
>     at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:201) ~[bedwars-plugin-22.2.jar:?]
>     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-349]
>     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
>     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-349]
>     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
>     at java.lang.Thread.run(Thread.java:831) ~[?:?]
> [20:16:11] [Server thread/INFO]: [BedWars1058] Disabling BedWars1058 v22.2
> [20:16:11] [Server thread/ERROR]: Error occurred while disabling BedWars1058 v22.2 (Is it up to date?)
> java.lang.ExceptionInInitializerError: null
>     at com.andrei1058.bedwars.BedWars.onDisable(BedWars.java:585) ~[bedwars-plugin-22.2.jar:?]
>     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-349]
>     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-349]
>     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
>     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-349]
>     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
>     at java.lang.Thread.run(Thread.java:831) ~[?:?]
> Caused by: java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.configuration.MainConfig.getInt(String)" because "com.andrei1058.bedwars.BedWars.config" is null
>     at com.andrei1058.bedwars.arena.Arena.<clinit>(Arena.java:105) ~[bedwars-plugin-22.2.jar:?]
>     ... 12 more
>     
> ```

Soo any solution? I have the same issue :(

**Comment by ehamawy** [comment]
having same issue on 1.8.8 paper server with mysql database

**Comment by tomkeuper** [comment]
Can you provide a full server log? and with latest version.

**Comment by tomkeuper** [comment]
Closed due to issue being stale
