### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Sohqil** [andrei1058/BedWars1058#40]
**Describe the bug**
I left the Debug Map while i was in the generator

[08:39:07 WARN]: [BedWars1058] Task #4022 for BedWars1058 v${gitVer}21.10.1-SNAPSHOT generated an exception
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911) ~[?:1.8.0_301]
        at java.util.ArrayList$Itr.next(ArrayList.java:861) ~[?:1.8.0_301]
        at com.andrei1058.bedwars.arena.tasks.GamePlayingTask.run(GamePlayingTask.java:200) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
        
        

**System:**
 - OS: Windows 11
 - Spigot
 - 1.8.8
 - 21.10.1

**Comment by DieselJS** [comment]
This was caused by the AFK system (according to comments in the code). I'm assuming that the plugin incorrectly handled how you left the arena which caused the AFK system to spit out an error. But you'd need an official comment from Andrei or another developer that understands more about the code and stack trace.

**Comment by Sohqil** [comment]
> This was caused by the AFK system (according to comments in the code). I'm assuming that the plugin incorrectly handled how you left the arena which caused the AFK system to spit out an error. But you'd need an official comment from Andrei or another developer that understands more about the code and stack trace.

I didnt make this plugin

**Comment by DieselJS** [comment]
> I didnt make this plugin

... I know you didn't. I was just explaining the error to you, and also providing a quick summary to the developer and other people who read this, as well as the people that might also be encountering this error. Hope this helps?

**Comment by tomkeuper** [comment]
Quite sure this has been fixed a long time ago. Reopen if needed make sure you are on the latest version
