### ISSUE TITLE
Heave 2 errors..

### ISSUE THREAD

**Issue by Areanydd** [andrei1058/BedWars1058#46]
**Describe the bug**
[20:43:28] [Server thread/ERROR]: Could not pass event InventoryClickEvent to HandyOrbs v2.1.3
org.bukkit.event.EventException: null
  at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[spigot.jar:git-Paper-1618]
  at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-Paper-1618]
  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Paper-1618]
  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[spigot.jar:git-Paper-1618]
  at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[spigot.jar:git-Paper-1618]
  at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Paper-1618]
  at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Paper-1618]
  at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-Paper-1618]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
  at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
  at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[spigot.jar:git-Paper-1618]
  at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[spigot.jar:git-Paper-1618]
  at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1618]
  at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1618]
  at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1618]
  at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
  at me.qKing12.HandyOrbs.Orbs.SugarCane.hyperActivity(SugarCane.java:130) ~[?:?]
  at me.qKing12.HandyOrbs.Orbs.OrbMenu$ListenUp.onInventoryClick(OrbMenu.java:341) ~[?:?]
  at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[spigot.jar:git-Paper-1618]
  ... 15 more

[18:53:08] [Server thread/WARN]: [HandyOrbs] Task #940927 for HandyOrbs v2.1.3 generated an exception
java.lang.NullPointerException: permission
    at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:172) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:112) ~[spigot.jar:git-Paper-1618]
    at me.qKing12.HandyOrbs.ConfigLoad.lambda$onCrystalPlace$2(ConfigLoad.java:400) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[spigot.jar:git-Paper-1618]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[spigot.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1618]
    at java.lang.Thread.run(Thread.java:829) [?:?]

**System (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04
 - Server software [e.g. spigot, paper] : Paper 
 - Server Version [e.g. 1.8.8] : 1.12.2
 - Plugin Version [e.g. 21.10.1]: 2.1.3

**Comment by marioded** [comment]
That's not related to Bedwars1058, that's related to HandyOrbs.

**Comment by andrei1058** [comment]
The version by qking is no longer supportes.
