### ISSUE TITLE
Arenas saved in slime format aren't reload after game ends

### ISSUE THREAD

**Issue by hugeBlack** [andrei1058/BedWars1058#508]
**Describe the bug**
Arenas saved in slime world format are unloaded and not reloaded after game ends, while normal worlds reloads as expected.

**To Reproduce**
1. Set up a arena and import it to slime world manager;
2. Play the arena and end the game;
3. Open game selection and you'll find the arena disappears;
4. Run `/swm list` and you'll see that the world is actually loaded, but not shown in arena selection, nor visible via `/bw arenaList`.

**Expected behavior**
The world of that arena should be loaded again

**System (please complete the following information):**
 - OS: Windows 11
 - Server software : PaperSpigot
 - Server Version : 1.18.1-216
 - Plugin Version : 22.3.4

**Additional context**
When I stopped my server, the log said this: 
```
[19:46:41 WARN]: [BedWars1058] Disabling arena: invasion
[19:46:41 ERROR]: Error occurred while disabling BedWars1058 v22.3.4 (Is it up to date?)
java.util.ConcurrentModificationException: null
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970) ~[?:?]
        at java.util.LinkedList$ListItr.next(LinkedList.java:892) ~[?:?]
        at com.andrei1058.bedwars.BedWars.onDisable(BedWars.java:604) ~[bedwars-plugin-22.3.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:515) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.disablePlugins(CraftServer.java:496) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1045) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:800) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1324) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

(I apologize for my poor English since I'm not a native speaker)

**Comment by EndMoyu** [comment]
个人自编译一份后重置地图仍然报错;w;
翻译是自己翻的嘛

I release one by myself and it still reported error in resetting the map

**Comment by hugeBlack** [comment]
简体中文：
欸，我这里1.18.1Paper测下来没问题，除了关服的时候swm会报错，但是没有什么影响，
能看下是啥报错误，以及服务器的版本吗qwq

翻译是自己翻的，有不准确的地方请指正

English:
I've tested this fix in 1.18.1 Paper and everything went smoothly, despite an exception thrown by SWM during server shutdown, which has no actual impact. Please leave the log, your version and server software.

**Comment by EndMoyu** [comment]
> 简体中文： 欸，我这里1.18.1Paper测下来没问题，除了关服的时候swm会报错，但是没有什么影响， 能看下是啥报错误，以及服务器的版本吗qwq
> 
> 翻译是自己翻的，有不准确的地方请指正
> 
> English: I've tested this fix in 1.18.1 Paper and everything went smoothly, despite an exception thrown by SWM during server shutdown, which has no actual impact. Please leave the log, your version and server software.

Bug等我朋友回来看看能不能复现下;w;
话说提交的pr居然给block了(

翻译 绝杀翻成突然死亡挺怪的
铁傀儡和蠹虫 击杀队伍后面直接扔's了
既然是简体中文建议所有句子最末尾的.换成句号
床摧毁的 不再能 个人看着有点怪，建议改成不能再
losses直接成负场了好家伙
respawnchat为什么要有三个感叹号(

- 核心:FlamePaper 1.8.9
- Java:Zulu jre8
- 系统:Debian 11

~~另外咱想用bungee来着，结果这插件bungee模式有影响游玩的bug~~
~~带的English只是给外国友人看的~~

**Comment by hugeBlack** [comment]
简体中文：
我回头拿1.8.9的端试一下，不过1.8.9是SWM，1.16+是Advanced SWM，两个api用法可能不太一样？

我是因为朋友英语不太好所以顺手翻译的，可能标点符号忘记改了（
最近比较忙，翻译问题的话你可以直接fork我的分支然后提pr（（
（不过losses好像就是失败场数的意思？我再去翻翻代码，看看这个placeholder具体是怎么用的hhh

English
It seems that SWM is used is 1.8.9 while Advanced SWM is used in 1.16+. The difference of usage between these two forks may cause this issue.

**Comment by EndMoyu** [comment]
> 简体中文： 我回头拿1.8.9的端试一下，不过1.8.9是SWM，1.16+是Advanced SWM，两个api用法可能不太一样？
> 
> 我是因为朋友英语不太好所以顺手翻译的，可能标点符号忘记改了（ 最近比较忙，翻译问题的话你可以直接fork我的分支然后提pr（（ （不过losses好像就是失败场数的意思？我再去翻翻代码，看看这个placeholder具体是怎么用的hhh
> 
> English It seems that SWM is used is 1.8.9 while Advanced SWM is used in 1.16+. The difference of usage between these two forks may cause this issue.

~~不用想确实是失败场数，以及看起来又有新同行竞争了(~~
~~已经fork了，至于pr过几天提，主要咱实在是菜~~
顺带又来了个药水BUG，挺呕的
1058的servertype是Bungee_Legacy

以下是log，太长了(
[文本(2022-05-16 223416).txt](https://github.com/andrei1058/BedWars1058/files/8700989/2022-05-16.223416.txt)

**Comment by hugeBlack** [comment]
看日志是swm的问题，但是刚刚测了下PaperSpigot1.8.8-445没问题
貌似因为是SWM特别挑端，甚至有些版本spigot本体都不行，开服直接崩也是离谱（
几个版本测试下来和PaperSpigot端的兼容性是最好的，你可以换个端试一下
不过我是在multiarena下测的，不过应该和这个没关系（？
(药水bug是隐身药水吗hhh

**Comment by EndMoyu** [comment]
> 看日志是swm的问题，但是刚刚测了下PaperSpigot1.8.8-445没问题 貌似因为是SWM特别挑端，甚至有些版本spigot本体都不行，开服直接崩也是离谱（ 几个版本测试下来和PaperSpigot端的兼容性是最好的，你可以换个端试一下 不过我是在multiarena下测的，不过应该和这个没关系（？ (药水bug是隐身药水吗hhh

是，喝完药瓶还在，隐身也只有实体隐身，别人能看见盔甲
隐身粒子挖坑很久了都没见安德烈和aj填坑(还有防爆玻璃，搭桥蛋cd等)
还有翻译增益的锋利 磨刀石 这好像是hyp繁体的叫法(，还有一些错字受的地方(急迫写击破hhh)

**Comment by EndMoyu** [comment]
> 看日志是swm的问题，但是刚刚测了下PaperSpigot1.8.8-445没问题 貌似因为是SWM特别挑端，甚至有些版本spigot本体都不行，开服直接崩也是离谱（ 几个版本测试下来和PaperSpigot端的兼容性是最好的，你可以换个端试一下 不过我是在multiarena下测的，不过应该和这个没关系（？ (药水bug是隐身药水吗hhh

![S20516-22243135](https://user-images.githubusercontent.com/85435560/168625471-88e0d562-1afb-4972-861f-5d9f9c9e4e8a.png)
~~笑，感觉不如bedwarsrel(~~

**Comment by hugeBlack** [comment]
低版本其实选择还是挺多的（不过bedwarsrel好像不支持swm？
要不是高版本只有这一个能用我也不会来修bug了（

**Comment by EndMoyu** [comment]
> 低版本其实选择还是挺多的（不过bedwarsrel好像不支持swm？ 要不是高版本只有这一个能用我也不会来修bug了（

不是好像，是确实
swm也是我碰1058之后才发现的，就没见其他小游戏插件支持(
~~另外早日run，这插件bug不少~~

**Comment by EndMoyu** [comment]
> > 低版本其实选择还是挺多的（不过bedwarsrel好像不支持swm？ 要不是高版本只有这一个能用我也不会来修bug了（
> 
> 不是好像，是确实 swm也是我碰1058之后才发现的，就没见其他小游戏插件支持( ~另外早日run，这插件bug不少~

防爆玻璃只要不完整包住 外面一炸就防爆了个寂寞
rejoin之后无工具
bungee模式会莫名其妙退出且玩家队伍依然存在，有时候等待大厅会出现两个同一个id的实体，也会为他分队
火球没有缓慢
隐身无脚印和搭桥蛋没有cd
swm世界，白日循环疑似不工作
剩下的忘了( 
睡了 醒了应该能记点 晚安
[1058 翻译 未完成修改](https://github.com/YukiEnd233/BedWars1058/blob/master/bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/ChineseSimplified.java)

**Comment by hugeBlack** [comment]
把防爆玻璃和隐身药水的bug修掉了
1.8的防爆玻璃测下来好像没问题（？，所以只改了1.18的
火球的缓慢可能是国内搞出来的？我以前玩的时候就没有

**Comment by EndMoyu** [comment]
咱有个疾速起床的addon，用那个addon防爆玻璃就有问题了 晚上再测测
火球缓慢确实有，至少起床1.5更新的时候有

**Comment by EndMoyu** [comment]
话说有打算用bungee模式吗
bungee有一个灵异事件的bug但是我不太好提issues，主要是这个bug复现抓不准但又经常碰见，但是一端一图就没这个问题了
但是咱没内存

**Comment by EndMoyu** [comment]
> 咱有个疾速起床的addon，用那个addon防爆玻璃就有问题了 晚上再测测 火球缓慢确实有，至少起床1.5更新的时候有

![S20517-20382121](https://user-images.githubusercontent.com/85435560/168815838-c788ceab-0f9a-42a1-b13e-592c68e63f68.png)
随便找了个国服视频 国际的图咱找不到

**Comment by EndMoyu** [comment]
已更换Paper1.8.8-445 药水瓶会自动清除但是隐身仍然无法隐藏盔甲，火球仍然可以透过防爆玻璃，swm仍然无法重置
玄学..

对插件源码删除了1.18的支持，不知道是不是因为这个原因（没配置明白jdk，使用zulu jdk 8跑出来的）
![S20518-22160459](https://user-images.githubusercontent.com/85435560/169064182-7f148d33-378c-43bf-a917-4d48278323c8.png)

**Comment by EndMoyu** [comment]
> 已更换Paper1.8.8-445 药水瓶会自动清除但是隐身仍然无法隐藏盔甲，火球仍然可以透过防爆玻璃，swm仍然无法重置 玄学..
> 
> 对插件源码删除了1.18的支持，不知道是不是因为这个原因（没配置明白jdk，使用zulu jdk 8跑出来的） ![S20518-22160459](https://user-images.githubusercontent.com/85435560/169064182-7f148d33-378c-43bf-a917-4d48278323c8.png)

等一下..好像可以重置，但是proxy里不显示，是1058的问题不是swm（
```[22:16:39] [Craft Scheduler Thread - 7/WARN]: Exception in thread "Craft Scheduler Thread - 7" 
[22:16:39] [Craft Scheduler Thread - 7/WARN]: org.apache.commons.lang.UnhandledException: Plugin BedWars1058 v22.3-SNAPSHOT generated an exception while executing task 668
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
	at com.andrei1058.bedwars.lobbysocket.ArenaSocket.formatUpdateMessage(ArenaSocket.java:89)
	at com.andrei1058.bedwars.lobbysocket.SendTask$1.run(SendTask.java:44)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
```

**Comment by hugeBlack** [comment]
看报错是lobbysocket的问题，估计是对bungee支持不好
修tnt的时候确实没考虑到火球，我去看一下
1.18的支持应该不影响，因为在启用插件的时候插件会去根据版本加载对应的versionsupport类
（bungee方面的问题你可以考虑自己去修一下，我只考虑会不会影响我玩hhh

**Comment by EndMoyu** [comment]
> 看报错是lobbysocket的问题，估计是对bungee支持不好 修tnt的时候确实没考虑到火球，我去看一下 1.18的支持应该不影响，因为在启用插件的时候插件会去根据版本加载对应的versionsupport类 （bungee方面的问题你可以考虑自己去修一下，我只考虑会不会影响我玩hhh

咱太菜了，哪天有空提一个吧（
但是看起来安德烈和aj都摆了
不知道rejoin会丢失工具修了没
隐身没粒子不知道会不会影响你玩hhh

**Comment by hugeBlack** [comment]
隐身粒子的话你应该去提feature request（
要加的话得改隐身那块的代码，也就是得对每个版本做适配
爆炸之所以能进去是因为爆炸直接调的是原版的爆炸算法，斜角冲击波可以直接进去，你放堵墙再拿火球炸就可以看到了
图中的摆法的话即便把玻璃换成黑曜石，冲击波照样能进去
要改的话得自己写爆炸算法，这又是另一个故事了（

**Comment by EndMoyu** [comment]
> 隐身粒子的话你应该去提feature request（ 要加的话得改隐身那块的代码，也就是得对每个版本做适配 爆炸之所以能进去是因为爆炸直接调的是原版的爆炸算法，斜角冲击波可以直接进去，你放堵墙再拿火球炸就可以看到了 图中的摆法的话即便把玻璃换成黑曜石，冲击波照样能进去 要改的话得自己写爆炸算法，这又是另一个故事了（

..好家伙画坑了属于是，从1月到现在还没修#292
早睡

**Comment by hugeBlack** [comment]
不知道怎么回事，刚刚发现22.3.4的所有isInvisibilityPotion方法全没了，然而这里开源的代码里并没有去掉。你可以自己编译一份1.8_R3和VersionSupport来解决问题

**Comment by IIHERO4** [comment]
> you want to change it, you have to write the explosion algorithm yourself, which is another story

you can use https://github.com/andrei1058/BedWars1058/pull/469 which just copies the nms implementation and add a check to whether a blast proof gass is standing before the 
shock wave

**Comment by tomkeuper** [comment]
Im quite sure this went offtopic, is this issue still relevant if so what is the problem? 

And lets keep it english only so we all know what is happening :)

**Comment by andrei1058** [comment]
try updating the plugin version
