### ISSUE TITLE
1.12 error

### ISSUE THREAD

**Issue by pereirafps** [andrei1058/BedWars1058#51]
[BedWars1058] Task #681 for BedWars1058 v${gitVer}21.10.1-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.entity.Player.showPlayer(org.bukkit.plugin.Plugin, org.bukkit.entity.Player)'
        at com.andrei1058.bedwars.support.version.v1_12_R1.v1_12_R1.spigotShowPlayer(v1_12_R1.java:666) ~[?:?]
        at com.andrei1058.bedwars.listeners.joinhandler.JoinListenerMultiArena.lambda$onJoin$0(JoinListenerMultiArena.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by andrei1058** [comment]
Use the proper report template.

**Comment by ajgeiss0702** [comment]
iirc this error happens if you use 1.12.0. Please use 1.12.2 if you are going to use 1.12
