### ISSUE TITLE
world already exists error

### ISSUE THREAD

**Issue by ProtoGhost** [andrei1058/BedWars1058#591]
[19:11:12 WARN]: [BedWars1058] Task #751 for BedWars1058 v22.01 generated an exception
java.lang.IllegalArgumentException: World solace already exists! Maybe it's an outdated SlimeWorld object?
        at com.grinderwolf.swm.nms.v1_8_R3.v1_8_R3SlimeNMS.addWorldToServerList(v1_8_R3SlimeNMS.java:102) ~[?:?]
        at com.grinderwolf.swm.nms.v1_8_R3.v1_8_R3SlimeNMS.generateWorld(v1_8_R3SlimeNMS.java:89) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.generateWorld(SWMPlugin.java:343) ~[?:?]
        at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.lambda$onEnable$1(SlimeAdapter.java:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-2894af04d]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**System**
 - OS:  Linux
 - Server software paperspigot
 - Server Version git-PaperSpigot-2894af04d (MC: 1.8.8)
 - Plugin Version bedwars-plugin-22.01
 - ![image](https://user-images.githubusercontent.com/67905221/185803093-07cedc6c-0b86-4438-9f21-5e4250c5bda8.png)

**Comment by andrei1058** [comment]
Does it happen at server startup or after a game?

**Comment by ProtoGhost** [comment]
It comes on startup

**Comment by tomkeuper** [comment]
Is this still up to date?

**Comment by tomkeuper** [comment]
Closed due to inactivity
