### ISSUE TITLE
SQLITE ERROR

### ISSUE THREAD

**Issue by TheWylot** [andrei1058/BedWars1058#62]
**Describe the bug**
this error is spaming on my console

**To Reproduce**
[07:03:35 WARN]: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
[07:03:35 WARN]:        at org.sqlite.DB.newSQLException(DB.java:383)
[07:03:35 WARN]:        at org.sqlite.DB.newSQLException(DB.java:387)
[07:03:35 WARN]:        at org.sqlite.DB.execute(DB.java:339)
[07:03:35 WARN]:        at org.sqlite.DB.executeUpdate(DB.java:363)
[07:03:35 WARN]:        at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[07:03:35 WARN]:        at com.andrei1058.bedwars.database.SQLite.setLevelData(SQLite.java:316)
[07:03:35 WARN]:        at com.andrei1058.bedwars.levels.internal.PlayerLevel.lambda$updateDatabase$0(PlayerLevel.java:247)
[07:03:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[07:03:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[07:03:35 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[07:03:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[07:03:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[07:03:35 WARN]:        at java.lang.Thread.run(Unknown Source)

**System (please complete the following information):**
 - OS: Windows Server 2019
 - Server software: Paper Spigot
 - Server Version: 1.8.8
 - Plugin Version 21.11

**Comment by Syrent** [comment]
I have a similar problem.

System:

- OS: Linux (Ubuntu 20.04)
- Server software: PaperMC
- Server Version: 1.8.8
- Plugin Version 21.11
