### ISSUE TITLE
Player is forced to be at spawn when setting up the Lobby. While Y is lower then 0 and higher than -64 (New Y problem)

### ISSUE THREAD

**Issue by LimeShep** [andrei1058/BedWars1058#636]
Bug Information:
- When you try to setup the spawn location "/bw setLobby" you get teleported automatically to spawn and can't move, fly or tp

Expected Behavior:
- The lobby should be set and let you go anywhere you want.

How to reproduce?
1. Download paper for 1.18.2
2. Add the plugin to the server (Version shown in system information)
3. Set lobby using cmd /bw setLobby

System Information:
- Windows Server
- SV = 1.18.2
- PV = 22.12-BETA or 22.9-BETA (22.7 doesn't work completely with 1.18.2)

Console Errors:
```
[18:32:03 WARN]: [BedWars1058] Task #656 for BedWars1058 v22.12-SNAPSHOT generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'bw leave' in com.andrei1058.bedwars.commands.bedwars.MainCommand(bw)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.listeners.Interact.lambda$onItemCommand$0(Interact.java:84) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: location
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1137) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.teleport(CraftEntity.java:558) ~[paper-1.18.2.jar:git-Paper-387]
        at com.andrei1058.bedwars.arena.Misc.moveToLobbyOrKick(Misc.java:72) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.subcmds.regular.CmdLeave.execute(CmdLeave.java:60) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.MainCommand.execute(MainCommand.java:150) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 11 more
[18:32:22 WARN]: [BedWars1058] Task #749 for BedWars1058 v22.12-SNAPSHOT generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'bw leave' in com.andrei1058.bedwars.commands.bedwars.MainCommand(bw)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.listeners.Interact.lambda$onItemCommand$0(Interact.java:84) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: location
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1137) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.teleport(CraftEntity.java:558) ~[paper-1.18.2.jar:git-Paper-387]
        at com.andrei1058.bedwars.arena.Misc.moveToLobbyOrKick(Misc.java:72) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.subcmds.regular.CmdLeave.execute(CmdLeave.java:60) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.MainCommand.execute(MainCommand.java:150) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 11 more
[18:32:27 WARN]: [BedWars1058] Task #750 for BedWars1058 v22.12-SNAPSHOT generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'bw leave' in com.andrei1058.bedwars.commands.bedwars.MainCommand(bw)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.listeners.Interact.lambda$onItemCommand$0(Interact.java:84) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: location
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1137) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.teleport(CraftEntity.java:558) ~[paper-1.18.2.jar:git-Paper-387]
        at com.andrei1058.bedwars.arena.Misc.moveToLobbyOrKick(Misc.java:72) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.subcmds.regular.CmdLeave.execute(CmdLeave.java:60) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.MainCommand.execute(MainCommand.java:150) ~[bedwars-plugin-22.12-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 11 more
```
(While logging into the server, "/bw leave" issue)

**Comment by tomkeuper** [comment]
I (MrCeasar) tested this with the user and can confirm this issue, 

Server was in MUTLIARENA mode and as soon as you go past y=0 you get stuck at the lobby location.
Applicable to newer versions only as you can build in the void.

Maybe a void tp issue?

**Comment by andrei1058** [comment]
I do manipulate player location. I'll have to investigate because I'm not really updated regarding new chunk coordinates.

Could be from lobby void tp feature (in lobby) which should be already configurable or from void kill feature (in game) perhaps.

**Comment by tomkeuper** [comment]
forgot the mention this issue in the commit but it will be configurable from now on. You can either disable or enable void tp and this will be documented on the wiki
