### ISSUE TITLE
Is it up to date? bug on enabling

### ISSUE THREAD

**Issue by MegaJeuxyt** [andrei1058/BedWars1058#645]
When i start my server, BedWars 1058 show me this :

[20:37:52 INFO]: [BedWars1058] Enabling BedWars1058 vgit-78ba3ed9-21.2-SNAPSHOT
[20:37:52 WARN]: [BedWars1058] Lobby location is not set!
[20:37:52 ERROR]: Error occurred while enabling BedWars1058 vgit-78ba3ed9-21.2-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.entity.EntityType$Builder net.minecraft.entity.EntityType$Builder.a(net.minecraft.entity.EntityType$IFactory, net.minecraft.entity.EntityClassification)'
        at com.andrei1058.bedwars.support.version.v1_16_R3.v1_16_R3.registerEntities(v1_16_R3.java:196) ~[?:?]
        at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:347) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:503) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:213) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:37:52 INFO]: [BedWars1058] Disabling BedWars1058 vgit-78ba3ed9-21.2-SNAPSHOT

**Comment by MegaJeuxyt** [comment]
my server running on Mohist 1.16.5

**Comment by Xxyuri2005xX** [comment]
try using BedWars1058 23.1.1, why you use 21.2?

**Comment by MegaJeuxyt** [comment]
it's the same, I already tested

**Comment by Xxyuri2005xX** [comment]
have you also tried on spigot or paper alone to see if it works? because bedwars without the NMS doesn't work and I wouldn't want mohist to have no NMS

**Comment by MegaJeuxyt** [comment]
is possible to add NMS to mohist or to find an equivalent of mohist with nms ?
