### ISSUE TITLE
bug while loading some maps

### ISSUE THREAD

**Issue by masood151117** [andrei1058/BedWars1058#670]
[20:14:53] [Server thread/INFO]: [BedWars1058] Load done: amazon2
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: java.util.zip.ZipException: zip END header not found
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1483)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1491)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1329)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1292)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:710)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at bedwars-plugin-23.2.jar//com.andrei1058.bedwars.api.util.ZipFileUtil.unzipFileIntoDirectory(ZipFileUtil.java:44)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at bedwars-plugin-23.2.jar//com.andrei1058.bedwars.maprestore.internal.InternalAdapter.lambda$onEnable$2(InternalAdapter.java:75)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:14:53] [Craft Scheduler Thread - 47 - BedWars1058/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[20:14:54] [Server thread/INFO]: Preparing start region for dimension minecraft:aquarium
[20:14:54] [Server thread/INFO]: Time elapsed: 9 ms
[20:14:54] [Server thread/INFO]: [BedWars1058] Loading arena: archway
[20:14:54] [Server thread/INFO]: [BedWars1058] Load done: aquarium

while loading some maps like this . and when i join these maps with bw join . bw setuparena and... these are completely empty .
Windows server 2019
JDK 19
Purpur 1.19.3
bedwars1058 latest version

**Comment by tomkeuper** [comment]
It looks like some of your maps are corrupt or have been changed manually 

There are also no steps to reproduce this error

**Comment by masood151117** [comment]
:/
