### ISSUE TITLE
When enabling or joining the server looks like this and if you enter a world bedwars when is set up end enabled the second player does not show up at the bw lobby and the game does not start

### ISSUE THREAD

**Issue by SimontechGaming** [andrei1058/BedWars1058#671]
[22:59:11 ERROR]: Error occurred while enabling BedWars1058 v23.2 (Is it up to date?)
java.lang.UnsupportedClassVersionError: com/andrei1058/bedwars/libs/sidebar/SidebarManager has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_361]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_361]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_361]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_361]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_361]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_361]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]
        at com.andrei1058.bedwars.sidebar.SidebarService.<init>(SidebarService.java:37) ~[?:?]
        at com.andrei1058.bedwars.sidebar.SidebarService.init(SidebarService.java:31) ~[?:?]
        at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:561) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:740) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_361]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_361]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]

**Comment by SimontechGaming** [comment]
and the scoreboard does not work

**Comment by tomkeuper** [comment]
You need to use java 11 and for 1.8 you might need to disable use-native-transport in server.properties.
https://discord.gg/ha8XQKZj
