### ISSUE TITLE
Error upgrades Menu

### ISSUE THREAD

**Issue by Max6468** [andrei1058/BedWars1058#703]
**Describe the bug**

When i open the upgrades menu, it give me an error in the console
**To Reproduce**
1. Play a game
2. Open upgrades Menu

**Expected behavior**

I put the error of the console here:
[20:46:54] [Server thread/ERROR]: Could not pass event PlayerInteractAtEntityEvent to BedWars1058 v23.2.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2104) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:74) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:13) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "{tier_   _color}Nivel 1: Proteccion I, §b{tier_  _cost} {tier_   _currency}"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:983) ~[?:?]
        at com.andrei1058.bedwars.upgrades.menu.MenuUpgrade.getDisplayItem(MenuUpgrade.java:100) ~[?:?]
        at com.andrei1058.bedwars.upgrades.menu.InternalMenu.open(InternalMenu.java:67) ~[?:?]
        at com.andrei1058.bedwars.upgrades.listeners.UpgradeOpenListener.onUpgradesOpen(UpgradeOpenListener.java:46) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        ... 18 more
**Screenshots**

**System (please complete the following information):**
 - OS:  Windows 10
 - Server software  Linux Server
 - Server Version  1.16.5
 - Plugin Version  23.2.1

**Additional context**

**Comment by tomkeuper** [comment]
Remove your language files and let it regenerate. The latest update changed the way we placholders are proccessed with upgrades.
Alternatively you can just delete the upgade parts in the language file.

example: 
https://github.com/andrei1058/BedWars1058/blob/9d2f1adb98bd5cd11c466de3b474e2462d76af1e/bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/English.java#L465-L469

**Comment by tomkeuper** [comment]
Next time please join the discord and ask there first :)
