### ISSUE TITLE
Game wont start and some players wont TP in queue.

### ISSUE THREAD

**Issue by Ultroneoucs** [andrei1058/BedWars1058#720]
**Describe the bug**
Game does not want to start and error with the plugin in console. Also when go into queue it wont TP the second player to the waiting spawn.

**To Reproduce**
1. Go into a bedwars game
2. Get second player to join with you.
The game wont start and the second player wont be TPed.

**Expected behavior**
All players are able to join and the game to start.

**Screenshots**
First Error:
```
16.03 20:01:50 [Server] WARN [BedWars1058] TOWER is not a valid v1_8_R3 material!
16.03 20:01:50 [Server] ERROR Error occurred while enabling BedWars1058 v23.2.1 (Is it up to date?)
```
Second Error:
```
16.03 20:05:18 [Server] ERROR Could not pass event InventoryClickEvent to BedWars1058 v23.2.1
16.03 20:05:18 [Server] INFO org.bukkit.event.EventException
16.03 20:05:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
16.03 20:05:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
16.03 20:05:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
16.03 20:05:18 [Server] INFO Caused by: java.lang.NullPointerException
16.03 20:05:18 [Server] INFO at com.andrei1058.bedwars.arena.Arena.addPlayer(Arena.java:550) ~[?:?]
16.03 20:05:18 [Server] INFO at com.andrei1058.bedwars.listeners.arenaselector.ArenaSelectorListener.onArenaSelectorClick(ArenaSelectorListener.java:68) ~[?:?]
16.03 20:05:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
16.03 20:05:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
16.03 20:05:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
16.03 20:05:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
16.03 20:05:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
```
**System (please complete the following information):**
 - OS: Whatever Apex Hosting Uses
 - Server software spigot
 - Server Version 1.8.8
 - Plugin Version 23.2.1

**Additional context**
I try to run the plugin just by itself by no fix to the problem.

**Comment by Ultroneoucs** [comment]
Also Scoreboard does not show up

**Comment by tomkeuper** [comment]
Use discord for support...
