### ISSUE TITLE
Bw leave Error

### ISSUE THREAD

**Issue by BurnBurst** [andrei1058/BedWars1058#731]
<[12:17:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'bw leave' in com.andrei1058.bedwars.commands.bedwars.MainCommand(bw)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-448]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: location.world
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1291) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1223) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftEntity.teleport(CraftEntity.java:548) ~[paper-1.19.3.jar:git-Paper-448]
        at com.andrei1058.bedwars.arena.Misc.moveToLobbyOrKick(Misc.java:74) ~[bedwars-plugin-23.2.1.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.subcmds.regular.CmdLeave.execute(CmdLeave.java:60) ~[bedwars-plugin-23.2.1.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.MainCommand.execute(MainCommand.java:150) ~[bedwars-plugin-23.2.1.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 22 more-->

**Expected behavior**
<When I do /bw leave It shows this error-->

**System (please complete the following information):**
 - OS:  Linux
 - Server software: Paper
 - Server Version 1.19.3
 - Plugin Version 23.2.1

**Comment by tomkeuper** [comment]
Join the support server and ask there first https://discord.gg/wXpmKsJN
