### ISSUE TITLE
mysql no connect

### ISSUE THREAD

**Issue by akillamrck** [andrei1058/BedWars1058#742]
server 1.8.8
paper
BedWars1058 - OpenSource 23.3

[06:16:39] [Server thread/ERROR]: Error occurred while enabling BedWars1058 v23.3 (Is it up to date?)
com.andrei1058.bedwars.libs.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'tx_isolation'
	at com.andrei1058.bedwars.libs.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.pool.HikariPool.checkFailFast(HikariPool.java:575) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
	at com.andrei1058.bedwars.database.MySQL.connect(MySQL.java:105) ~[?:?]
	at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:395) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLException: Unknown system variable 'tx_isolation'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.getTransactionIsolation(ConnectionImpl.java:3198) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.andrei1058.bedwars.libs.hikari.pool.PoolBase.checkDefaultIsolation(PoolBase.java:480) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:443) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.pool.PoolBase.setupConnection(PoolBase.java:411) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[?:?]
	at com.andrei1058.bedwars.libs.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
	... 12 more

**Comment by hamza-cskn** [comment]
i have same problem too.

**Comment by xiaozhu52055** [comment]
You can try it with MySQL version 5.7

**Comment by WitheredWinter** [comment]
I have the same problem on BW1058 version v23.3 too

**Comment by WitheredWinter** [comment]
this still happens on BW1058 v23.12.2 while using Paper1.8.8 and JDK11
