### ISSUE TITLE
[Solved] java.lang.IllegalArgumentException: Team §a already exists in this scoreboard - Kicked out while joining the game

### ISSUE THREAD

**Issue by crescent-admin** [andrei1058/BedWars1058#791]
(Using translation software, the content may look strange, sorry)
I am using BedWars1058-23.3, the servers are paper-1.18.2-388 and waterfall-1.18-488,

serverType: BUNGEE_LEGACY

The moment a player joins the Arena from the lobby, it is kicked out of the Arena and returned to the lobby. Arena console has no exception (ikun lost connection: Disconnected), the following error appeared on the Waterfall console:
--------------------------------------------------------------
[14:16:41 ERROR]: [/127.0.0.1:57005|ikun] <-> DownstreamBridge <-> [bedwars4_testmap1] - encountered exception
java.lang.IllegalArgumentException: Team §a already exists in this scoreboard
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:248) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.18-488.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:16:41 INFO]: [ikun] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by FallenCrystal** [comment]
尝试以下办法:
  
  - 在`waterfall.yml`中禁用`disable_tab_list_rewrite`. `disable_tab_list_rewrite: false`
  - 确保卸载任何有关强制干涉计分板的插件/附属. 如果你可以 你也可以使用TAB和占位符来代替这些附属 这里不再多说具体操作
  - 公民过老也会导致这种情况 如果你的公民不是最新的 请尝试更新到最新版

如果你尝试了第一步仍然出现这种情况 那么这就是绝对的backend服务器问题. 如果使用了会修改计分板的附属/插件(NPC插件也会) 请尝试更新它们或卸载它们.

此问题与BungeeCord, Bedwars1058和服务端(如果你没有用奇怪的fork)并没有直接关系. 首先检查附属插件 而不是将问题报告插件本身,

**Comment by RedEdge-Engine** [comment]
This bug is related to a plugin, it's confirmed. For debug, I ran server with 
- Bedwars1058.jar (latest)
- Protocollib.jar (latest)
The issue has been fixed in many plugins. Bedwars1058, still haven't fixed!
Make note, @andrei1058

**Comment by RedEdge-Engine** [comment]
as @FallenCrystal said, 
Set `disable_tab_list_rewrite:` to false. The issue is caused by scoreboard, there's no link to it

**Comment by RedEdge-Engine** [comment]
That bug wasn't a thing in previous bedwars1058 versions

**Comment by FallenCrystal** [comment]
🤔 
im trying not to confuse something. the language of my answers is based on the questioner. i didn't expect anyone else to read the same issue.
but setting `disable_tab_list_rewrite` to false does prevent the proxy from throwing an exception and kicking the player. although it is possible that they were indeed assigned the same scoreboard team for other reasons.
this includes going to other servers, etc. this solution also works with the interference scoreboard team plugin. (u can tackle players who are bored and walking around the edge of the visual distance of the znpcs, for example.)

> my English is not very good. if u don't understand or u think i might have misinterpreted something. please ask questions. I'll try to explain what is in it.

**Comment by andrei1058** [comment]
Will update the plugin documentation with that info.
