### ISSUE TITLE
a new bug

### ISSUE THREAD

**Issue by Epsillan** [andrei1058/BedWars1058#84]
**Describe the bug**
i added a MysQl database and the plugin got disbled and it show this error 
************************************************************************************************************************************
[20:16:42 ERROR]: Error occurred while enabling BedWars1058 v21.11 (Is it up to date?)
java.lang.UnsupportedClassVersionError: com/andrei1058/bedwars/libs/hikari/HikariConfig has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_292]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_292]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_292]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_292]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_292]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_292]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_292]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_292]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
        at com.andrei1058.bedwars.database.MySQL.connect(MySQL.java:74) ~[?:?]
        at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:376) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[20:16:42 INFO]: [BedWars1058] Disabling BedWars1058 v21.11
**************************************************************************************************************************************
**To Reproduce**

**Expected behavior**
you fix this if you want 
**Screenshots**

**System (please complete the following information):**
 - Server software  spigot
 - Server Version 1.8.8
 - Plugin Version latest

**Additional context**
no

**Comment by MherZaqaryan** [comment]
#83
