### ISSUE TITLE
1.8.8 Spitting out random error codes on join.

### ISSUE THREAD

**Issue by lezetho** [andrei1058/BedWars1058#872]
**Describe the bug**

Whenever I attempt join my 1.8.8 server, it tells me `Connection Refused` and console was spitting out lots of errors at a rapid pace.
**To Reproduce**

Install **ONLY** Bedwars1058 ( i installed latest ). Install [1.8.8](https://getbukkit.org/get/hNiHm0tuqAg1Xg7w7zudk63uHr0xo48D) Spigot from here, install via [Pterodactyl](https://pterodactyl.io/), and start server.

**Expected behavior**

Lets me log in without any issues.
**Screenshots**

![image](https://github.com/andrei1058/BedWars1058/assets/126505858/693e5374-384f-4e4a-8c9b-1217153b97e4)

**System (please complete the following information):**
 - OS: Linux ( maybe )
 - Server software: Spigot
 - Server Version: 1.8.8
 - Plugin Version: latest

**Additional context**

ERROR LOG:
`[09:47:32 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
        at io.netty.channel.epoll.Native.read(Native Method) ~[2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [2server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[09:47:32 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
        at io.netty.channel.epoll.Native.read(Native Method) ~[2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [2server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[09:47:32 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
        at io.netty.channel.epoll.Native.read(Native Method) ~[2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [2server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[09:47:32 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
        at io.netty.channel.epoll.Native.read(Native Method) ~[2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) [2server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755) [2server.jar:git-Spigot-21fe7`

**Comment by lezetho** [comment]
Never mind, seems like all I needed to do is upgrade to 1.12.2 and add ViaVersion / ViaBackwards / ViaRewind
