### ISSUE TITLE
level incorect counter on tab and name tag

### ISSUE THREAD

**Issue by AIGLE25** [andrei1058/BedWars1058#879]
Describe the Bug:

the level counters are sometime incorect on the tab and on the name tag and scoreboard.
![image](https://github.com/andrei1058/BedWars1058/assets/68445450/f7b1d3ec-d12a-4972-b6ab-5aaa1411c866)

To Reproduce:

connect to the server and sometime i have "trying to get stats data of an unloaded player

System (please complete the following information):

OS: Windows
Server Software: Paper
Server Version: 1.8.8
Plugin Version: 23.10-SNAPSHOT
Additional context

[16:30:23 ERROR]: Could not pass event PlayerJoinEvent to BedWars1058 v23.10-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: java.lang.IllegalStateException: Trying to get stats data of an unloaded player!
        at com.andrei1058.bedwars.stats.StatsManager.get(StatsManager.java:52) ~[?:?]
        at com.andrei1058.bedwars.sidebar.BwSidebar.getPlaceholders(BwSidebar.java:278) ~[?:?]
        at com.andrei1058.bedwars.sidebar.BwSidebar.setContent(BwSidebar.java:87) ~[?:?]
        at com.andrei1058.bedwars.sidebar.SidebarService.giveSidebar(SidebarService.java:134) ~[?:?]
        at com.andrei1058.bedwars.listeners.joinhandler.JoinListenerMultiArena.onJoin(JoinListenerMultiArena.java:91) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 15 more

**Comment by andrei1058** [comment]
any database details?

**Comment by AIGLE25** [comment]
i don't use any database , just the basic shop.db

**Comment by AIGLE25** [comment]
> any database details?

i don't use any database , just the basic shop.db
