### ISSUE TITLE
bw1058 doesnt start

### ISSUE THREAD

**Issue by BOplaid** [andrei1058/BedWars1058#928]
**Describe the bug**
bw1058 doesnt start on mc 1.20.2 java 17.

**To Reproduce**
set up a paper server with mc 1.20.2 and java 17.
put bedwars1058 in plugins.

**Expected behavior**
i expected for bw1058 to actually start up.

**System (please complete the following information):**
 - OS: Linux
 - Server software Paper
 - Server Version 1.20.2
 - Plugin Version 23.11.2
**Additional context**
the part in the console where it refuses the boot up:
[19:34:25 INFO]: [BedWars1058] Enabling BedWars1058 v23.11.2
[19:34:25 ERROR]: Error occurred while enabling BedWars1058 v23.11.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.api.server.VersionSupport.registerVersionListeners()" because "com.andrei1058.bedwars.BedWars.nms" is null
        at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:219) ~[bedwars-plugin-23.11.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-291]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-291]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[19:34:25 INFO]: [BedWars1058] Disabling BedWars1058 v23.11.2
[19:34:25 ERROR]: Error occurred (in the plugin loader) while disabling BedWars1058 v23.11.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.andrei1058.bedwars.BedWars.onDisable(BedWars.java:590) ~[bedwars-plugin-23.11.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.2.jar:git-Paper-291]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.2.jar:git-Paper-291]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-291]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.configuration.MainConfig.getInt(String)" because "com.andrei1058.bedwars.BedWars.config" is null
        at com.andrei1058.bedwars.arena.Arena.<clinit>(Arena.java:112) ~[bedwars-plugin-23.11.2.jar:?]
        ... 16 more

**Comment by andrei1058** [comment]
I have sent a new bedwars jar on Discord. LMK if it works with java 17 now.

**Comment by BOplaid** [comment]
ok

**Comment by BOplaid** [comment]
IT WORKED!
