### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SMarc1** [andrei1058/BedWars1058#963]
```
[18:51:30 ERROR]: Could not pass event GameEndEvent to BedWars1058 v23.12.2
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
        at com.andrei1058.bedwars.arena.upgrades.HealPoolTask.removeForArena(HealPoolTask.java:90) ~[?:?]
        at com.andrei1058.bedwars.arena.upgrades.HealPoolListner.onEnd(HealPoolListner.java:34) ~[?:?]
        at org.imanity.imanityspigot.events.executor.asm.generated.GeneratedEventExecutor249.execute(Unknown Source) ~[?:?]
        at org.imanity.imanityspigot.executor.EventExecutorGenerator.lambda$create$1(EventExecutorGenerator.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
        at com.andrei1058.bedwars.arena.Arena.checkWinner(Arena.java:1985) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1035) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by andrei1058** [comment]
We are not officially supporting imanityspigot ...
