### ISSUE TITLE
1.8.8 Paper throws out 'An exceptionCaught() event was fired'

### ISSUE THREAD

**Issue by Terry-mcgit** [andrei1058/BedWars1058#981]
**Describe the bug**
Whenever I join my 1.8.8 paper server though waterfall server,it tells me 'Exception Connecting: NativeIoException : recvaddress(..) failed: Connection reset by peer' and the console threw lots of errors.

**To Reproduce**
1.Install BedWars1058,ViaVersion... on 1.8.8 Paper(full plugin list is shown in screenshots) and start server.
2.Use 1.8.9 join the server.
3.It throws errors.

**Expected behavior**
Let me join in with any version(1.8.9+)

**Screenshots**

![picture](https://github.com/andrei1058/BedWars1058/assets/102499513/181332d2-ddcb-43b5-b18d-f7de1e19ce7e)
![picture](https://github.com/andrei1058/BedWars1058/assets/102499513/c4130216-7316-4112-8724-ef95d0a5cd6c)
![picture](https://github.com/andrei1058/BedWars1058/assets/102499513/0472cdbd-c54d-49fc-b290-429d346f5fd6)

**System (please complete the following information):**
 - OS: Linux CentOS7.6
 - Server software: Paper <- Waterfall
 - Server Version: 1.8.8
 - Plugin Version: 23.12.2

**Additional context**
log:
`
[07:35:30] [Netty Epoll Server IO #1/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
        at io.netty.channel.epoll.Native.read(Native Method) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by Terry-mcgit** [comment]
It runs on MULTIARENA mode. I just connect it in to a Waterfall server

**Comment by ImYenil** [comment]
It's not bug Set use-native-transport to false in your server.properties file.

**Comment by Terry-mcgit** [comment]
Thank you
