### ISSUE TITLE
Error in console: Could not pass event TeamEliminatedEvent

### ISSUE THREAD

**Issue by krystian987** [andrei1058/BedWars1058#984]
**Describe the bug**
Error in console:
[08:43:52] [Server thread/ERROR]: Could not pass event TeamEliminatedEvent to BedWars1058 v23.12.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1620]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.andrei1058.bedwars.listeners.DamageDeathMove.onRespawn(DamageDeathMove.java:548) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor248.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:688) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer$1.respawn(CraftPlayer.java:1840) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.andrei1058.bedwars.listeners.DamageDeathMove.lambda$onDeath$2(DamageDeathMove.java:487) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
	at com.andrei1058.bedwars.arena.upgrades.HealPoolTask.removeForTeam(HealPoolTask.java:112) ~[?:?]
	at com.andrei1058.bedwars.arena.upgrades.HealPoolListner.teamDead(HealPoolListner.java:40) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor305.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
	... 20 more

**To Reproduce**
I don't know how to reproduce this error, but it appears very often in the console

**System:**
 - OS: Linux
 - Server software Paper
 - Server Version 1.12.2
 - Plugin Version 23.12.2

**Comment by Lsy-291** [comment]
This is a known healing pool removal bug that occurs during traversal modification
