### ISSUE TITLE
Erros in console

### ISSUE THREAD

**Issue by HanielCota** [andrei1058/BedWars1058#995]
[12:41:02 ERROR]: Could not pass event NPCRemoveEvent to BedWars1058 v23.12.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getNearbyEntities(double, double, double)" because the return value of "net.citizensnpcs.api.npc.NPC.getEntity()" is null
        at com.andrei1058.bedwars.support.citizens.CitizensListener.removeNPC(CitizensListener.java:64) ~[bedwars-plugin-23.12.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor481.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-446]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-446]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-446]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.citizensnpcs.api.npc.AbstractNPC.destroy(AbstractNPC.java:163) ~[Citizens-2.0.33-b3358.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.destroy(CitizensNPC.java:124) ~[Citizens-2.0.33-b3358.jar:?]
        at br.com.ystoreplugins.lib.helper.entity.npc.impl.CitizensNpcFactory$NpcImpl.delete(Unknown Source) ~[yPlugins (2).jar:?]
        at com.ystoreplugins.ypayments.method.npc.NpcUpdater.update(NpcUpdater.java:17) ~[?:?]
        at com.ystoreplugins.ypayments.Main.lambda$reload$0(Main.java:127) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-446]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-446]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by ImYenil** [comment]
> [12:41:02 ERROR]: Could not pass event NPCRemoveEvent to BedWars1058 v23.12.2 java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getNearbyEntities(double, double, double)" because the return value of "net.citizensnpcs.api.npc.NPC.getEntity()" is null at com.andrei1058.bedwars.support.citizens.CitizensListener.removeNPC(CitizensListener.java:64) ~[bedwars-plugin-23.12.2.jar:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor481.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-446] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-446] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-446] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at net.citizensnpcs.api.npc.AbstractNPC.destroy(AbstractNPC.java:163) ~[Citizens-2.0.33-b3358.jar:?] at net.citizensnpcs.npc.CitizensNPC.destroy(CitizensNPC.java:124) ~[Citizens-2.0.33-b3358.jar:?] at br.com.ystoreplugins.lib.helper.entity.npc.impl.CitizensNpcFactory$NpcImpl.delete(Unknown Source) ~[yPlugins (2).jar:?] at com.ystoreplugins.ypayments.method.npc.NpcUpdater.update(NpcUpdater.java:17) ~[?:?] at com.ystoreplugins.ypayments.Main.lambda$reload$0(Main.java:127) ~[?:?] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-446] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-446] at java.lang.Thread.run(Thread.java:840) ~[?:?]
When does this error occur?

**Comment by ImYenil** [comment]
> [12:41:02 ERROR]: Could not pass event NPCRemoveEvent to BedWars1058 v23.12.2 java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getNearbyEntities(double, double, double)" because the return value of "net.citizensnpcs.api.npc.NPC.getEntity()" is null at com.andrei1058.bedwars.support.citizens.CitizensListener.removeNPC(CitizensListener.java:64) ~[bedwars-plugin-23.12.2.jar:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor481.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-446] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-446] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-446] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at net.citizensnpcs.api.npc.AbstractNPC.destroy(AbstractNPC.java:163) ~[Citizens-2.0.33-b3358.jar:?] at net.citizensnpcs.npc.CitizensNPC.destroy(CitizensNPC.java:124) ~[Citizens-2.0.33-b3358.jar:?] at br.com.ystoreplugins.lib.helper.entity.npc.impl.CitizensNpcFactory$NpcImpl.delete(Unknown Source) ~[yPlugins (2).jar:?] at com.ystoreplugins.ypayments.method.npc.NpcUpdater.update(NpcUpdater.java:17) ~[?:?] at com.ystoreplugins.ypayments.Main.lambda$reload$0(Main.java:127) ~[?:?] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-446] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-446] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-446] at java.lang.Thread.run(Thread.java:840) ~[?:?]

When does this error occur?

**Comment by HanielCota** [comment]
I don't no, i simple interact in npc

**Comment by ImYenil** [comment]
> I don't no, i simple interact in npc

Fixed
